name: dscexporter
summary: Export metrics and data from a Discourse server
description: |
  Download data from a Discourse server, then extract requested metrics to MySQL, CSV, or JSON.

base: core22
type: app
version: git
confinement: strict
grade: stable

apps:
  dscexporter:
    command: bin/dscexporter
    plugs:
      [network, network-bind]

parts:
  dscexporter:
    plugin: go
    build-snaps: [go/latest/stable]
    source: https://github.com/lvoytek/discourse-data-exporter
    source-type: git
