name: dscexporter
summary: Export metrics and data from a Discourse server
description: |
  Download data from a Discourse server, then extract requested metrics to MySQL, CSV, or JSON.

base: core24
type: app
version: git
confinement: strict
grade: stable

apps:
  dscexporter:
    command: dscexporter
    plugs:
      [network, network-bind]

parts:
  dscexporter:
    plugin: go
    build-snaps: [go/latest/stable]
    source: .
    source-type: git
    override-build: |
      go build -o $SNAPCRAFT_PART_INSTALL/dscexporter *.go

